# Generated by Django 4.1.5 on 2023-02-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testlar', '0002_resultlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultList',
        ),
    ]
