# Generated by Django 4.1.5 on 2023-02-08 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='url_contest',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
