# Generated by Django 4.1.5 on 2023-02-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_url_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='start_time',
        ),
    ]
